### ISSUE TITLE
[EVM-45] The publish action no longer works

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/evm-tableland#414]
Starting this week the publish action fails with the error
```
Downloading compiler 0.8.19
Error: scripts/deploy.ts(3,38): error TS[23](https://github.com/tablelandnetwork/evm-tableland/actions/runs/4821511960/jobs/8587480590#step:9:24)07: Cannot find module '../typechain-types' or its corresponding type declarations.
Error: scripts/upgrade.ts(3,38): error TS2307: Cannot find module '../typechain-types' or its corresponding type declarations.
npm ERR! code 2
npm ERR! path /home/runner/work/evm-tableland/evm-tableland
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-04-27T15_20_20_930Z-debug-0.log
Error: Error: Unable to publish @tableland/evm v4.2.1 to NPM. 
npm publish --access public exited with a status of 2.
    at Object.publish (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/npm.ts:112:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

ProcessError: npm publish --access public exited with a status of 2.
    at normalizeResult (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/node_modules/@jsdevtools/ez-spawn/lib/normalize-result.js:31:1)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/node_modules/@jsdevtools/ez-spawn/lib/async.js:79:1)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:[27](https://github.com/tablelandnetwork/evm-tableland/actions/runs/4821511960/jobs/8587480590#step:9:28)6:12)
```

full failure here: https://github.com/tablelandnetwork/evm-tableland/actions/runs/4821511960/jobs/8587480590

<sub>[EVM-45](https://linear.app/tableland/issue/EVM-45/the-publish-action-no-longer-works)</sub>

**Comment by joewagner** [comment]
Re-opening, this is still broken.
